modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "fuelgoeshereif"
version = "${version}"

displayName = "Fuel Goes Here (Iron Furnaces)"
# displayURL = "https://github.com/unilock/FuelGoesHereIF"

authors = "kate"
description = '''
Makes furnace fuel always go in the fuel slot first (with Iron Furnaces)

A partial derivative of "Fuel Goes Here" by LobsterJonn:
https://www.curseforge.com/minecraft/mc-mods/fuelgoeshere
'''


[[dependencies.fuelgoeshereif]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fuelgoeshereif]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fuelgoeshereif]]
modId = "ironfurnaces"
mandatory = true
versionRange = "[3.3.0,)"
ordering = "NONE"
side = "BOTH"
