modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "fuelgoeshereironfurnaces"
version = "${version}"

displayName = "Fuel Goes Here (Iron Furnaces)"
# displayURL = "https://changeme.dev/"
# logoFile = "icon.png"

authors = "Kate, LobsterJonn"
description = '''
blahhh
'''
credits = '''
LobsterJonn for Fuel Goes Here
https://www.curseforge.com/minecraft/mc-mods/fuelgoeshere
'''


[[dependencies.fuelgoeshereironfurnaces]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fuelgoeshereironfurnaces]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fuelgoeshereironfurnaces]]
modId = "ironfurnaces"
mandatory = true
versionRange = "[3.3.0,)"
ordering = "NONE"
side = "BOTH"
